# github repository actions 페이지에 나타날 이름
name: Deploy - CI/CD Pipeline

# event trigger
# main이나 develop 브랜치에 push가 되었을 때 실행
on:
  push:
    # dev 나 main 으로 push 를 하거나
    branches:
      - main
      - 305-bugfix-deploy-error
    # dev 가 pull request 를 생성시
#  pull_request:
#    branches:
#      - dev
env:
  DOCKER_IMAGE_TAG_NAME: film-fly
  AWS_REGION: ap-northeast-2

jobs:
  deploy-front:
    # 실행 환경
    runs-on: ubuntu-latest

    steps:
      # SOURCE 단계 - 저장소 Checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          SOURCE_DIR: "front/html"
          DEST_DIR: "dist"
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
